base_images:
  aro:
    name: automation-flavors
    namespace: stackrox
    tag: aro-0.3.8
  eks:
    name: automation-flavors
    namespace: stackrox
    tag: eks-0.3.1
  osd:
    name: automation-flavors
    namespace: stackrox
    tag: osd-0.3.6
  rosa:
    name: automation-flavors
    namespace: stackrox
    tag: rosa-0.3.8
  ubi-minimal:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: apollo-ci
    namespace: stackrox
    tag: stackrox-test-0.3.56
releases:
  latest:
    release:
      channel: stable
      version: "4.6"
resources:
  '*':
    requests:
      cpu: 2000m
      memory: 4000Mi
test_binary_build_commands: .openshift-ci/dispatch.sh test-binary-build-commands
tests:
- as: ocp-4-6-other-qa-e2e-tests
  optional: true
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: openshift-newest-qa-e2e-tests
    test:
    - ref: stackrox-e2e
    workflow: ipi-aws
  timeout: 5h0m0s
zz_generated_metadata:
  branch: master-ocp-4-6
  org: stackrox
  repo: stackrox
