base_images:
  ubi-minimal:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: apollo-ci
    namespace: stackrox
    tag: stackrox-test-0.3.56
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 2000m
      memory: 4000Mi
test_binary_build_commands: .openshift-ci/dispatch.sh test-binary-build-commands
tests:
- always_run: false
  as: qa-e2e-tests
  optional: true
  run_if_changed: ^((generated|image|operator|pkg|make|deploy|scripts)/.*|Makefile|status\.sh|EXPECTED_GO_VERSION)
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: openshift-newest-qa-e2e-tests
    test:
    - ref: stackrox-e2e
    workflow: ipi-aws
  timeout: 5h0m0s
- always_run: false
  as: operator-e2e-tests
  optional: true
  run_if_changed: ^((generated|image|operator|pkg|make|deploy|scripts)/.*|Makefile|status\.sh|EXPECTED_GO_VERSION)
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: openshift-4-operator-e2e-tests
    test:
    - ref: stackrox-e2e
    workflow: ipi-aws
  timeout: 5h0m0s
- always_run: false
  as: ui-e2e-tests
  optional: true
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: ocp-ui-e2e-tests
    test:
    - ref: stackrox-e2e
    workflow: ipi-aws
  timeout: 5h0m0s
- as: weekly-ocp-13-qa-e2e-tests
  cron: 0 5 * * 2
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: openshift-newest-qa-e2e-tests
    test:
    - ref: stackrox-e2e
    workflow: ipi-aws
  timeout: 5h0m0s
- as: gke-ui-e2e-tests
  optional: true
  steps:
    test:
    - ref: stackrox-e2e
  timeout: 5h0m0s
- as: gke-postgres-ui-e2e-tests
  optional: true
  steps:
    test:
    - ref: stackrox-e2e
  timeout: 5h0m0s
- as: weekly-ocp-13-ui-e2e-tests
  cron: 0 5 * * 2
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: ocp-ui-e2e-tests
    test:
    - ref: stackrox-e2e
    workflow: ipi-aws
  timeout: 5h0m0s
- as: weekly-ocp-13-operator-e2e-tests
  cron: 0 5 * * 2
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: openshift-4-operator-e2e-tests
    test:
    - ref: stackrox-e2e
    workflow: ipi-aws
  timeout: 5h0m0s
zz_generated_metadata:
  branch: master
  org: stackrox
  repo: stackrox
  variant: ocp-4-13
