base_images:
  ubi-minimal:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: apollo-ci
    namespace: stackrox
    tag: stackrox-test-0.3.58
releases:
  latest:
    release:
      channel: fast
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 2000m
      memory: 4000Mi
test_binary_build_commands: .openshift-ci/dispatch.sh test-binary-build-commands
tests:
- as: test-deploy-acs
  optional: true
  steps:
    cluster_profile: aws
    test:
    - ref: stackrox-deploy-acs
    workflow: ipi-aws
  timeout: 5h0m0s
zz_generated_metadata:
  branch: master
  org: stackrox
  repo: stackrox
  variant: my-branch
